### ISSUE TITLE
System freeze on Recore A6

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Rebuild#16]
Recore A6 will experience a system freeze during boot-up. This is an issue carried over from Refactor v3.2.0. 

It looks as though using the device tree from Refactor v3.1.3 does work. It is attached to this issue. Somewhere in that patch lies the answer. 

As a workaround, it seems as though the file `/boot/dtb/allwinner/sun50i-a64-recore-a6.dtb` can be replaced with the one from v3.1.3 (also attached) and that should do the trick. 

[Diff_and_dtb.zip](https://github.com/intelligent-agent/Rebuild/files/14653016/Diff_and_dtb.zip)

**Comment by Avatarsia** [comment]
Copy the File in Home Folder of Debian User
DL  here https://github.com/intelligent-agent/Refactor/blob/v3.1.x/roles/linux_preparation/files/sun50i-a64-recore-a6.dtb

sudo mount -o remount, rw /boot
sudo cp -R "/home/debian/sun50i-a64-recore-a6.dtb" "/boot/dtb-6.6.22-current-sunxi64/allwinner/sun50i-a64-recore-a6.dtb"
sync
sudo mount -o remount, ro /boot
sudo reboot

**Comment by Avatarsia** [comment]
also change the MCU Port in the Printer.cfg

sed -i '/^\[mcu\]$/,/^\[mcu ar100\]$/ {
  /^\[mcu\]$/ {
    s/.*/# The STM32F031 mcu\
&/
  }
  /^\[mcu ar100\]$/ {
    s/.*/# The AR100 mcu\
&/
  }
  /serial: \/dev\/ttyS2/ {
    s/serial: \/dev\/ttyS2/serial: \/dev\/ttyS4/
  }
}' /home/debian/printer_data/config/printer.cfg

**Comment by eliasbakken** [comment]
There is a difference of RAM chips on A5, A6 and A7, A8. There is a PR addressing this.

**Comment by eliasbakken** [comment]
[sun50i-a64-recore-a6-dtbs.zip](https://github.com/intelligent-agent/Rebuild/files/14963453/sun50i-a64-recore-a6-dtbs.zip)
This zip file has the 1.5 V and the 1.36 V versions of the DTBs to make comparisons

**Comment by eliasbakken** [comment]
to check what the current voltage level is at: 
```sudo cat /sys/kernel/debug/regulator/regulator_summary | grep dram```

**Comment by eliasbakken** [comment]
This seems to be resolved and merged into main. It can be re-opened again if the issues comes up again.
