### ISSUE TITLE
Moonraker sometimes has problems with the SSH service. 

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Rebuild#27]
Moonraker sometimes has an error on first boot. This seems to be the offending line:
`systemctl show -p ActiveState,SubState --value klipper KlipperScreen moonraker ssh` 
In Fluidd, it will look something like this: 
![image-ssh](https://github.com/intelligent-agent/Rebuild/assets/3756249/212463e4-84f8-4dac-af74-8e1dc14b8e36)

**Comment by eliasbakken** [comment]
This is the log file from Moonraker as reported by Olle
[message(1).txt](https://github.com/intelligent-agent/Rebuild/files/15314245/message.1.txt)

**Comment by obgr** [comment]
I just reflashed again.
The error message did not show. 

I checked the services recognized by moonraker and ssh was not there.
after a restart of moonraker, ssh made the list.

It may be likely that this issue occur if klipper starts before ssh.

**Comment by goeland86** [comment]
It could also be that you need to restart moonraker so the service for definition updates the database with some entries for it to work properly too.

**Comment by eliasbakken** [comment]
I've added a `systemctl daemon-reload` as a final command in the install script. I'm not sure if that does anything.
Having thought about this it should not make any difference the order in which the services starts. Moonraker checks if the services are running or not, so they should be able to be in any state.

**Comment by eliasbakken** [comment]
I've not seen this issue since the daemon-reload was added. I think we close it for now since it no longer appears. If it persists as a problem, we can reopen the issue.
