### ISSUE TITLE
Use specific verisons of the software instead of rolling releases

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Rebuild#36]
The relevant software is: 
- Armbian build: Now 24.05 branch. 
- KlipperScreen
- Klipper
- Moonraker
- ustreamer

**Comment by obgr** [comment]
Tags:
Klipper screen: v0.4.1
Fluidd: v1.30.0
Mainsail: v2.11.2
ustreamer: [v6.12](https://github.com/pikvm/ustreamer/releases/tag/v6.12)

Does not really do tags, find a relevant commit or keep rolling?
Moonraker:
Klipper:

**Comment by eliasbakken** [comment]
I'm not sure what this will mean for updates. For Klipper there are tags, but very infrequent. 
I think we should try and release an RC1 for now that has a working KlipperScreen so the pre-release is working. Then we can continue looking into what the consequences are. 
Ideally we vet the updates as well, so we only allow certain waypoints with all sottware working together.

**Comment by eliasbakken** [comment]
This seems to be a problem for the update system. Closing for now.
