### ISSUE TITLE
Add possibility to start ssh from OctoPrint

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Rebuild#40]
In Mainsail and Fluidd, we have the option to start the SSH server if it is disabled by a timeout. In OctoPrint, we do not have this option. It is still possible to enable ssh by using the USB-C port and then enabling it via a terminal, but it should be possible to do this from the user interface. 
The idea has also been to allow this to be done from Reflash, but that functionality is not yet implemented. Here are some options:
1) We fix the refactor_octoprint plugin. It should be enough to remove the section about boot medium. This will also allow us to display the version of Rebuild we are currently on. 
2) We add a command to the on/off dropdown if that is possible. 
![image](https://github.com/intelligent-agent/Rebuild/assets/3756249/2173e7ab-1503-453b-b2ba-f40474893125)
3) We fix Reflash and allow SSH to be enabled from there only.

**Comment by obgr** [comment]
Octoprint supports plugins in a more open way than fluidd/mainsail.
There is a possibillity to write a plugin that manages this, or to try to find an existing service.

**Comment by eliasbakken** [comment]
Yeah, I think fixing the plugin is the easiest way to handle this. I'll try
that first.

fre. 31. mai 2024, 11:57 skrev Olle ***@***.***>:

**Comment by eliasbakken** [comment]
PR ready
